### ISSUE TITLE
Fatal error: Class 'Mobile_Detect' not found

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/useragent#4]
Hi,

bekomme einen Fatal Error:

> "ErrorException" thrown in /Applications/MAMP/htdocs/abc/redaxo/src/addons/rex_useragent/lib/UserAgent.php on line 56
> Fatal error: Class 'Mobile_Detect' not found

LG
Oliver

**Comment by olien** [comment]
OK. Du hast MobileDetect abgekoppelt.
Aber wohin??

LG
Oliver

**Comment by phoebusryan** [comment]
Hast du die Githubversion benutzt? In der normalen Version über den Installer (sollte (denke ich so)) es eigentlich gehen. Sonst muss ich schauen.

Die Githubversion ist aktuell nicht einsatzfähig, das stimmt.

**Comment by olien** [comment]
Hi, habe die Github Version. Wie heisst das Addon im Installer??

LG
Oliver

**Comment by phoebusryan** [comment]
user_agent ... Das lief über Sascha. Er hats aber anscheinend gelöscht. Meine Version werde ich aber demnächst fertigstellen und dann im installer bereitstellen. :-)

Ich habe dir die letzte funktionierende Version grade via Skype geschickt.

**Comment by olien** [comment]
Cool. Danke!
